app_name = "awesome web"
log_level = "DEBUG"

[mysql]
  database = "awesome"
  ext = "ext"
  ip = "127.0.0.1"
  password = 123456
  port = 3306
  user = "dj"

[redis]
  ip = "127.0.0.1"
  port = 73812

[server]
  ports = [10000,10001,10002]
  protocols = ["http","https","port"]
